elastic-ipfs/infrastructure

.gitignore, README.md, put-file.sh, terraform/main.tf, terraform/modules/api-gateway-to-s3/api-gateway-to-s3.md, terraform/modules/api-gateway-to-s3/auth.tf, terraform/modules/api-gateway-to-s3/log.tf, terraform/modules/api-gateway-to-s3/main.tf, terraform/modules/api-gateway-to-s3/variables.tf, terraform/modules/indexing-subsystem/indexing-subsystem.md, terraform/modules/indexing-subsystem/main.tf, terraform/modules/indexing-subsystem/variables.tf, terraform/variables.tf
- Creates Bucket
- Creates API Gateway resources that integrate with bucket
- Configures necessary policies and roles
- Configures API Logging to CloudWatch
- S3 State Backend
- Modularization 
- Basic project description
- Default Tagging
=> API Gateway To S3

terraform/peer-subsystem/main.tf
Already going to be able to get metrics directly from Cloudwatch to managed Grafana
=> [WIP] - [NA-000] - Uninstall Cloudwatch Exporter

terraform/publishing-subsystem/locals.tf, terraform/publishing-subsystem/main.tf
- Update stortheindex URL to staging
- Create and configure DLQ
- Deprecated bucket ACL property**
=> [REVIEW] - [NA-000] - Deadletter queue

terraform/bucket-to-indexer-lambda/main.tf, terraform/modules/lambda-from-s3/auth.tf, terraform/modules/lambda-from-s3/log.tf, terraform/modules/lambda-from-s3/main.tf, terraform/modules/lambda-from-s3/variables.tf
- Consistency between lambda-from-s3 and lambda-from-sqs
=> [WIP] - [NA-000] - Multiple environment variables for lambda

terraspace/README.md, terraspace/app/modules/lambda-from-sqs/auth.tf, terraspace/app/modules/lambda-from-sqs/lambda-from-sqs.md, terraspace/app/modules/lambda-from-sqs/log.tf, terraspace/app/modules/lambda-from-sqs/main.tf, terraspace/app/modules/lambda-from-sqs/variables.tf, terraspace/app/stacks/indexing/auth.tf, terraspace/app/stacks/indexing/bucket-mirroring-trigger/README.md, terraspace/app/stacks/indexing/bucket-mirroring-trigger/bucket-mirror.js, terraspace/app/stacks/indexing/bucket-mirroring-trigger/package-lock.json, terraspace/app/stacks/indexing/bucket-mirroring-trigger/package.json, terraspace/app/stacks/indexing/bucket-mirroring-trigger/run-dotstorage-prod-0.sh, terraspace/app/stacks/indexing/bucket-mirroring-trigger/single-file-manual-triger.js, terraspace/app/stacks/indexing/bucket-mirroring-trigger/sqs-message-sender.js, terraspace/app/stacks/indexing/indexing.md, terraspace/app/stacks/indexing/locals.tf, terraspace/app/stacks/indexing/main.tf, terraspace/app/stacks/indexing/outputs.tf, terraspace/app/stacks/indexing/tfvars/base.tfvars, terraspace/app/stacks/indexing/tfvars/us-west-2/prod.tfvars, terraspace/app/stacks/indexing/variables.tf, terraspace/app/stacks/shared/outputs.tf, terraspace/app/stacks/shared/shared.md
- Code imported from Terraform "indexing-subsystem" module. It was renamed to "indexing"
- New variables allow environment naming flexibility
- prod.tfvars keeps all existing stuff with the same name but the policies: Redundant word "policy" was removed.
- base.tfvars follows namespacing pattern defined in https://filecoinproject.slack.com/archives/C02BZPRS9HP/p1650986348274689?thread_ts=1646828696.183769&cid=C02BZPRS9HP
- Getting docker image URL from ECR repo object instead of hardcode
- Outputs from shared are used instead of remote_state
- Metrics namespaces segregated by environment
- Updating docs with input/output descriptions
tfsec fixes: 
tflint fixes: Description for all inputs and outputs
Note: Current production state was also copied to the newer S3 backend
<details> …
=> [REVIEW] - [NA-000] - Terraspace indexing stack

terraspace/app/stacks/indexing/indexing.md, terraspace/app/stacks/indexing/locals.tf, terraspace/app/stacks/indexing/tfvars/base.tfvars, terraspace/app/stacks/indexing/variables.tf, terraspace/app/stacks/publishing/auth.tf, terraspace/app/stacks/publishing/locals.tf, terraspace/app/stacks/publishing/main.tf, terraspace/app/stacks/publishing/publishing.md, terraspace/app/stacks/publishing/tfvars/base.tfvars, terraspace/app/stacks/publishing/tfvars/us-west-2/prod.tfvars, terraspace/app/stacks/publishing/variables.tf
- Code imported from Terraform "publishing-subsystem" module.
- tflint fixes
- Updating docs
Note: Current production state was also copied to the newer S3 backend
<details>
<summary>Expected output from TF_ENV=prod terraspace plan publishing:</summary>
```
Building .terraspace-cache/us-west-2/prod/stacks/publishing
Built in .terraspace-cache/us-west-2/prod/stacks/publishing
Current directory: .terraspace-cache/us-west-2/prod/stacks/publishing
=> terraform plan -input=false
Acquiring state lock. This may take a few moments...
aws_ecr_repository.ecr_repo_publisher_lambda: Refreshing state... [id=publisher-lambda]
aws_sqs_queue.ads_topic_dlq: Refreshing state... [id=https://sqs.us-west-2.amazonaws.com/505595374361/advertisements-topic-dlq]
aws_s3_bucket.ipfs_peer_ads: Refreshing state... …
```
=> [WIP] - [NA-000] - Terraspace publishing stack

terraspace/app/stacks/peer/main.tf
Adding my outbound IP to connect to EKS cluster through kubectl
=> [REVIEW] - [NA-000] - Added my outbound IP to access the cluster

terraspace/app/stacks/bucket-to-indexer-lambda/bucket-to-indexer-lambda.md, terraspace/app/stacks/indexing/indexing.md, terraspace/app/stacks/indexing/main.tf, terraspace/app/stacks/indexing/tfvars/base.tfvars, terraspace/app/stacks/indexing/variables.tf, terraspace/app/stacks/peer-kubernetes-components/tfvars/base.tfvars, terraspace/app/stacks/peer-kubernetes-components/tfvars/us-west-2/prod.tfvars, terraspace/app/stacks/shared/auth.tf, terraspace/app/stacks/shared/outputs.tf, terraspace/app/stacks/shared/shared.md, terraspace/app/stacks/shared/tfvars/base.tfvars, terraspace/app/stacks/shared/variables.tf
- Dotstorage bucket read policy per env
- Updates docs
=> [REVIEW] - [NA-000] - env bucket read policy 

terraspace/app/modules/dynamodb/auth.tf, terraspace/app/stacks/peer/main.tf, terraspace/app/stacks/shared/auth.tf
A safer way of renaming policies (Because it requires them to be recreated)
=> [REVIEW] - [NA-000] - Create before destroy policies

terraspace/app/stacks/peer-kubernetes-components/helm.tf, terraspace/app/stacks/peer-kubernetes-components/helm/argocd-apps/templates/fluentd-lambda.yaml, terraspace/app/stacks/peer-kubernetes-components/helm/argocd-apps/values.yaml
Adding fluentd for clouwatch logs
=> [REVIEW] - [NA-000] - Fluentd for cloudwatch logs

terraspace/app/modules/lambda-from-sqs/lambda-from-sqs.md, terraspace/app/stacks/indexing/indexing.md, terraspace/app/stacks/indexing/locals.tf, terraspace/app/stacks/indexing/main.tf, terraspace/app/stacks/indexing/tfvars/base.tfvars, terraspace/app/stacks/indexing/variables.tf, terraspace/app/stacks/peer-kubernetes-components/peer-kubernetes-components.md, terraspace/app/stacks/peer-kubernetes-components/tfvars/base.tfvars, terraspace/app/stacks/peer/peer.md, terraspace/app/stacks/publishing/publishing.md, terraspace/app/stacks/shared/auth.tf, terraspace/app/stacks/shared/main.tf, terraspace/app/stacks/shared/outputs.tf, terraspace/app/stacks/shared/shared.md, terraspace/app/stacks/shared/tfvars/base.tfvars, terraspace/app/stacks/shared/variables.tf
- Deploy new tables (V1), handle permissions and ENV vars
- Reduce concurrency to 8 (As now we're handling with batches)
- Update docs
=> [REVIEW] - [NA-000] -  Tables v1

terraspace/app/stacks/shared/tfvars/base.tfvars
Read comment thread https://github.com/ipfs-elastic-provider/ipfs-elastic-provider-indexer-lambda/pull/54#discussion_r914067375
=> [REVIEW] - [NA-000] - rename table

terraspace/app/stacks/bucket-mirror/bucket-mirror.md, terraspace/app/stacks/bucket-mirror/config-and-start.sh, terraspace/app/stacks/bucket-mirror/main.tf, terraspace/app/stacks/bucket-mirror/tfvars/base.tfvars, terraspace/app/stacks/bucket-mirror/variables.tf, utils/bucket-mirror/bucket-mirror.js, utils/bucket-mirror/config.js, utils/bucket-mirror/retry-wrapper.js, utils/bucket-mirror/sqs-message-sender.js, utils/bucket-mirror/test-local-run.sh
- Introducing more reliability through retries strategy
- Suffixing .CAR files
- "skipExists: true" so indexer lambda doesn't have to reprocess a CAR file that it already has
- Organize env variables and default values through "config.js" file (consistency with other services implementations)
=> [REVIEW] - [NA-000] - Bucket mirror script improvements

README.md
Fixes https://github.com/elastic-ipfs/infrastructure/issues/128
=> [WIP] - [NA-000] - update readme

.github/workflows/terraspace.yaml, terraspace/app/modules/cluster-autoscaler/auth.tf, terraspace/app/stacks/publishing/main.tf, terraspace/tfsec.yml
- Exclude encryption at rest rules
- Ignore public advertisement bucket
- Ignore cluster autoscaller IAM policy
=> [REVIEW] - [NA-000] - tfsec with exclude/ignore rules

packer/peer-e2e-testing/build.pkr.hcl, terraspace/app/stacks/peer-e2e-testing/auth.tf, terraspace/app/stacks/peer-e2e-testing/tfvars/base.tfvars
- Add policy to allow SSM
- Start SSM agent
- Replacing "_" in names to "-"
=> Enabling Session Manager Access

terraspace/app/modules/lambda/auth.tf, terraspace/app/stacks/bucket-to-indexer-lambda/tfvars/us-east-2/dev.tfvars, terraspace/app/stacks/bucket-to-indexer-lambda/tfvars/us-east-2/prod.tfvars, terraspace/app/stacks/bucket-to-indexer-lambda/tfvars/us-west-2/prod.tfvars
- statement_id_prefix (because of "for_each")
- update variable name in all tfvars
=> [WIP] - [NA-000] - Fix for multiple SNS lambda integration

terraspace/app/stacks/dns-certificate/main.tf, terraspace/app/stacks/dns/tfvars/us-west-2/staging.tfvars
=> [REVIEW] - [NA-000] - Update record value

terraspace/app/stacks/peer-kubernetes-components/helm.tf, terraspace/app/stacks/peer-kubernetes-components/peer-kubernetes-components.md, terraspace/app/stacks/peer-kubernetes-components/tfvars/base.tfvars, terraspace/app/stacks/peer-kubernetes-components/variables.tf, terraspace/app/stacks/peer/auth.tf, terraspace/app/stacks/peer/main.tf, terraspace/app/stacks/peer/outputs.tf, terraspace/app/stacks/peer/peer.md, terraspace/app/stacks/peer/tfvars/base.tfvars, terraspace/app/stacks/peer/variables.tf
=> [WIP] - [NA-000] - Bitswap config table

terraspace/app/stacks/peer-kubernetes-components/tfvars/us-west-2/prod.tfvars
=> [WIP] - [NA-000] - Fix: add database policy to prod

terraspace/app/stacks/peer/tfvars/base.tfvars
=> [READY] - [NA-000] - c6i.2xlarge as base instance type

terraspace/app/stacks/peer/main.tf
- Add default tags to launch_template_tags
- Segregate IAM roles
Already applied to dev env
=> [WIP] - [NA-000] - Default tags to EKS EC2 nodes

terraspace/app/stacks/bucket-to-indexer-lambda/tfvars/us-west-2/prod.tfvars, terraspace/app/stacks/shared/tfvars/us-west-2/prod.tfvars
Infrastructure is already up-to-date. This PR is to ensure code reflects what is already in the cloud.
=> [REVIEW] - [NA-000] - Connect prod-eipfs with prod-pickup

terraspace/app/stacks/peer/locals.tf
Also remove now useless fined grained egress metrics.
Applied to dev.
=> [WIP] - [NA-000] - Open egress to all internet in all ports. 

.github/workflows/pr-comment-terraspace.yaml
Fix for https://github.com/elastic-ipfs/infrastructure/actions/runs/4045292360/jobs/6956567391
=> [REVIEW] - [NA-000] - Write statuses permission

.github/dependabot.yml, .github/workflows/pr-comment-terraspace.yaml, .github/workflows/workflow-verifier.yaml, .vscode/settings.json
Remove deprecated set-output command + introduce dependabot for GH actions
=> [WIP] - [NA-000] - Workflows: Update deprecated commands and Introduce Dependabot

.github/workflows/pr-comment-terraspace.yaml, .github/workflows/pull-request-verifier.yaml
=> [WIP] - [NA-000] - Fix bug approval state

.github/workflows/pr-comment-terraspace.yaml
approval check should work if you get 2 or more approvals.
fixes: https://github.com/elastic-ipfs/elastic-ipfs/issues/28
License: MIT
=> chore: fix approval check in ci
